#!/bin/bash

[ -z "$3" ] && group=default
[ -n "$3" ] && group=$3

[[ "x$1" = "x--genCache" && -n "$2" ]] && { /home/pi/piLogger/bin/exportJSON $group $2 ; exit 0 ; }
[[ "x$1" = "x--genCache" ]] && { /home/pi/piLogger/bin/exportJSON default ; exit 0 ; }
[ -f /home/pi/piLogger/html/cache/sensorData.${1}.json ] && { cat /home/pi/piLogger/html/cache/sensorData.${1}.json ; exit 0 ; }
[ -f /home/pi/piLogger/html/cache/sensorData.json ] && { cat /home/pi/piLogger/html/cache/sensorData.json ; exit 0 ; }
/home/pi/piLogger/bin/exportJSON default
